[package]
name = "tracing-configuration"
version = "0.1.1"
edition = "2021"
description = "serializable configuration for a dynamic tracing-subscriber"
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/tracing-configuration"
repository = "https://github.com/aatifsyed/tracing-configuration"

[dependencies]
io-extra = "0.2.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
tracing-appender = "0.2.3"
tracing-core = { version = "0.1.32", default-features = false }
tracing-subscriber = { version = "0.3.18", features = [
    "std",
    "fmt",
    "chrono",
    "json",
    "ansi",
], default-features = false }
